controller_frequency: 8

TrajectoryPlannerROS:
  max_vel_x: 0.5 
  min_vel_x: 0.1 
  max_vel_theta: 2
  min_vel_theta: -2 

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 2.5
  acc_lim_x: .6
  acc_lim_y: .6

  sim_time: 2.0
  controller_frequency: 8

  vx_samples: 10.0
  vtheta_samples: 10.0

  pdist_scale: 0.6 
  gdist_scale: 0.8 
  occdist_scale: 0.01

  holonomic_robot: false
  
  publish_cost_grid_pc: true